version: 2

sources:
  - name: raw
    description: "Raw data schema loaded externally (via loader)"
    tables:
      - name: raw_sales
        description: "Sales data loaded from CSV via Docker loader"
        columns:
        - name: date
          description: "Date"
        - name: product
          description: "Product name"
        - name: price
          description: "Product price"
        - name: quantity
          description: "Sale quantity"
        tests:
          - dbt_expectations.expect_table_row_count_to_be_between:
              name: "positive_number_rows"
              description: "Ensure number of rows > 0"
              arguments:
                min_value: 0
                strictly: true
